# Dockerfile

FROM node:16-alpine

ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET

WORKDIR /app
COPY package.json package-lock.json ./


COPY . .
RUN npm run build


EXPOSE 3000
CMD ["node", "build"]